#!/bin/csh -f

set BF = `tput bold`
set RM = `tput sgr0`

echo $BF'Updating webpages using git'$RM

# using the file "finish" as the marker for when this was done last time
find . -newer finish -exec git add \{} \;
# prepare the git commit message
touch /tmp/message
find . -newer finish -exec ls \{} >> /tmp/message \;
git commit -F /tmp/message

git push -u origin main

rm /tmp/message
touch finish

# end of script
