#!/bin/csh -f

set BF = `tput bold`
set RM = `tput sgr0`

echo $BF'Updating webpages using git'$RM

# ADD
# using the file "finish" as the marker for when this was done last time
find . \( -name ".git" -prune -o -newer finish \) \( ! -name ".git" \) -exec git add \{} \;

# COMMIT
# prepare the git commit message
touch /tmp/message
# which will consist just of all the file names that have been changed
find . \( -name ".git" -prune -o -newer finish \) \( ! -name ".git" \) -type f -print >> /tmp/message
git commit --allow-empty-message -F /tmp/message

# PUSH
git push -u origin main

# Cleanup
rm /tmp/message
touch finish

# end of script
